[database]
path = "."

[family.mike]
first_name = "Mike"
last_name = "Bogey"
age = 30
children = ["John", "Bob"]

[family.alice]
first_name = "Alice"
last_name = "Bogey"
age = 25
children = ["John", "Bob"]

[family.john]
first_name = "John"
last_name = "Bogey"
age = 10
children = []

[family.bob]
first_name = "Bob"
last_name = "Bogey"
age = 8
children = []
